export const environment = {
  production: true,
  appname: 'DocuManager',
  appnamesmall: 'DM+',
  version: '1.0',
  companyname: 'Rendimos, LTDA',
  yearscopyrigth: '2017-2018',
  currentuser: 'documanagerwebuser',
  dbconsultas: 'DMConsultas',
  apiurl: 'http://186.145.16.130:8082/documanager.api/public',
  urlFilesUploads: 'http://186.145.16.130:8082/documanager.api/public',
  // apiurl: 'http://localhost:8082/documanager.api/public',
  // urlFilesUploads: 'http://localhost:8082/documanager.api/public',
  urlFilesDownload: 'http://186.145.16.130:8082/documanager.api/public',
  urlfacebook: 'https://www.facebook.com/ebert.zerpa',
  urltwitter: 'https://twitter.com/ebertzerpa',
};
