export const environment = {
  production: true,
  appname: 'ScriptForms',
  appnamesmall: 'S+',
  companyname: 'RENDIMOS, LTDA',
  yearscopyrigth: '2017-2018',
  currentuser: 'documanagerwebuser',
  dbconsultas: 'SFConsultas',
  // apiurl: 'http://localhost:8082/documanager.api/public',
  apiurl: 'http://186.145.16.130:8082/documanager.api/public',
  urlFilesUploads: 'http://186.145.16.130:8082/documanager.api/public/files/uploads/',
  urlFilesDownload: 'http://186.145.16.130:8082/documanager.api/public/files/',
  urlfacebook: 'https://www.facebook.com/ebert.zerpa',
  urltwitter: 'https://twitter.com/ebertzerpa',
};
